name: Deploy FastAPI App

on:
  push:
    branches:
      - main  # Deploy when changes are pushed to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Pull Docker Image
        run: docker pull abdraman/fastapi-app-image:latest  # Replace with your actual username

      - name: Stop & Remove Old Container (if exists)
        run: |
          docker stop fastapi_app || true
          docker rm fastapi_app || true

      - name: Run Docker Container
        run: |
          docker run -d --name fastapi_app -p 8000:8000 abdraman/fastapi-app-image:latest  # Replace with your actual username
